environment:
  name: test
  project: cdf-bootcamp-28-test
  validation-type: test
  selected:
    - modules/bootcamp/data_foundation
    - modules/bootcamp/ice_cream_api
    - modules/bootcamp/use_cases/oee

variables:
  modules:
    bootcamp:
      # Variables shared by modules
      icapi_ds_external_id: ds_icapi
      icapi_space_name: icapi_dm_space
      ice_cream_api:
        tokenUri: ${IDP_TOKEN_URL}
        cdfProjectName: ${CDF_PROJECT}
        scopes: ${IDP_SCOPES}
        icapi_extractors_source_id: ${ICAPI_EXTRACTORS_CLIENT_ID}
        icapi_extractors_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID}
        icapi_extractors_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET}
        icapi_extractors_pause_transformations: False
        # icapi_extractors_scheduleHourly: "*/1 * * * *"
      use_cases:
        oee:
          data_pipeline_oee_source_id: 7a7a97ea-78e1-4f44-8e16-3b8646f9a81b
          uc_oee_ds_external_id: ds_uc_oee
          oee_space_name: oee_ts_space
          data_pipeline_oee_client_id: ${DATA_PIPELINE_OEE_CLIENT_ID}
          data_pipeline_oee_client_secret: ${DATA_PIPELINE_OEE_CLIENT_SECRET}
      data_foundation:
        data_developer_source_id: ${DATA_DEVELOPER_SOURCE_ID}